### ISSUE TITLE
Where should the value of the "$Prize" field be displayed?

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/thumbwar-ios-client#1]
This was not addressed in the specs

**Comment by CodySwannGT** [comment]
This was not addressed in the specs

**Comment by smummolo** [comment]
We should have included that in the post view in the stream - let me talk to randy , good catch

**Comment by CodySwannGT** [comment]
Awesome. Please attach the mock or link to the mock here she you get it. Thanks

**Comment by jiakeliu** [comment]
This is a priority item, because the prize content could be more engaging than the bet itself, and at the very least amplifies the interesting level of the bet.
I'm not a designer, but how about displaying the prize like this? 
![prizescreen](https://cloud.githubusercontent.com/assets/1039583/6800454/d3a6694c-d1db-11e4-9292-1ecaf050f2ee.png)

**Comment by adamespn** [comment]
This is really cool but we can't implement it unless
1) You match this up with bet creation screen
2) You explain how the user will actually know to say "I can down a gallon of milk" and then separately say "$10 if I can down it in under a minute". The prize value appears to contain actual bet info.
That's actually a tall order, so if we can't iron everything out with this by Monday I'm going to kick it to the backlog.

**Comment by jiakeliu** [comment]
The prize field should be open ended with a text length constraint of 140 characters. The bet info can involve monetary value or not. The ordering in the image should match up with the revamped bet creation screen.

**Comment by adamespn** [comment]
I'm trying to picture how this actual screen comes about.

I go to the fridge. 3 year old Bobby says "Daddy don't drink all the milk".

I think "I'm gonna do a thumbwar".

I open the app. I tap POST.

Somewhere I type "I can down a gallon of milk"

Then somewhere else I think to type "$10 if I can down it in a minute"?

That does not seem logical.

I love this screen and I want this scenario to be supported. Im just not seeing how this content flows from a user into the app.

**Comment by jiakeliu** [comment]
Another way to create the same post is "I can down a gallon of milk in a minute." and then in the "What's the stake?" field just type "$10". I don't think we should limit how the user posts the Stake content, since it can also be something more verbose like "A steak dinner" or "Put on a wig and a dress at the next ball game". 

![creation](https://cloud.githubusercontent.com/assets/1039583/6882022/adf7356c-d534-11e4-9e29-a356892c698b.png)

**Comment by jiakeliu** [comment]
By the way, can you see what users are typing into the $Prize field to date? Can I see a few examples?

**Comment by adamespn** [comment]
Great question. I usually type "hdhdhhdhd" or such. Could win $5 if I drink a half gallon and $10 if I drink the whole gallon? Or is that going down the rabbit hole?

**Comment by jiakeliu** [comment]
That's going down the rabbit hole. Only scenario maybe that the opponent can up the ante or change the bet when they accept/decline the challenge, but let's hold off on implementing that.

For now do you think we can implement the Stake field as specified in this ticket or do you need more info?
