### ISSUE TITLE
Performance: Follower/Following count

### ISSUE THREAD

**Issue by jiakeliu** [gunnertech/thumbwar-ios-client#125]
Users want to see follower/following count in Profile view show up quicker to avoid confusion

**Comment by husseinm** [comment]
This would require either a server side change. Either for a new api method that provides only follower counts and then a separate longer request for the actual list - that would only cut down time ~100ms...

The only way to truly correct this would be to include the data as part of the user profile request so that the counts are included with the won/lost/push counts and the name/basic info of the profile allowing the count to load at the same time as the name. Would require a few changes to the model on the server side though. @CodySwannGT Opinion there?

A deployment server instead of Heroku would definitely help the issue, but not perfectly remedy it. Not sure how we want to approach this...
