### ISSUE TITLE
Create alerts for "Your Facebook friend 'xyz' joined Thumbwar"

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/thumbwar-ios-client#26]

**Comment by CodySwannGT** [comment]
@adamespn let's discuss how to make this happen

**Comment by adamespn** [comment]
@CodySwannGT you will need to create and push an alert of a new type - just give me the type.
@smummolo I need an icon for this alert type and I need to know what happens when you tap this alert. I am assuming that this alert type, when tapped, would open up your friend's profile screen (I can't think of anything else for it to open up). If that's the case we need to resolve the questions in #11 and #47

**Comment by CodySwannGT** [comment]
Yeah, and it's a bit more involved with that.

What I'm going to need from us is:

1) When a user signs in for the first time (aka registers) - you'll have to POST the facebook ids of his facebook friends as I can't access that info on the server.

2) I'll write a background process on the sever that loops through the POSTed ids and creates alerts as needed.

I'm assigning this to myself until I have the API endpoint written and documented.

**Comment by CodySwannGT** [comment]
This is now part of the /login api endpoint https://github.com/gunnertech/thumbwar-api#authentication

Just need to pass those upon login.
