### ISSUE TITLE
Can't submit comment or dismiss keyboard on iPhone 5(s)

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/thumbwar-ios-client#29]
![img_4363](https://cloud.githubusercontent.com/assets/292923/5986978/e3c1a666-a8e1-11e4-9536-6294c92222ba.PNG)
![img_4362](https://cloud.githubusercontent.com/assets/292923/5986979/e616eab6-a8e1-11e4-831e-555b426f3f68.PNG)

**Comment by CodySwannGT** [comment]
We never got design for submitting comments, so we did what we could, but there are clearly bugs.

This is actually a hard bug to fix, so before we go down that road, I'm wondering if our comment design is even acceptable.

**Comment by CodySwannGT** [comment]
@smummolo - got anything?

**Comment by jiakeliu** [comment]
Let's tackle this sooner rather than later because people (me included) can't test the app properly without an iPhone 5s or 6.

For the comment field, let's add the placeholder gray text "Add a comment..."  And replace the "Go" button text with "ADD". Also, since I can't see the text field as the keyboard is blocking it, does the field expand in size when a user types multiple lines? Here's a video illustration: https://vine.co/v/OYTgeUFBdJg 

For the keyboard bug, can we make the view scroll-able with the comment field pushed up by the keyboard once the keyboard pops up (just like in the video)?

**Comment by smummolo** [comment]
Can I get a screenshot?



On Feb 8, 2015, at 7:54 AM, Cody Swann <notifications@github.com> wrote:

@smummolo - got anything?

**Comment by adamespn** [comment]
Complete - two devices remain to test - one may not be tested until tomorrow

**Comment by jiakeliu** [comment]
Still seeing the same issue:
![imag2224](https://cloud.githubusercontent.com/assets/1039583/6882179/59fdb63e-d539-11e4-9a0f-890f67c873f1.jpg)

I assume there's a back arrow at the top of the screen? But since I can't scroll I'm stuck at this view.

 Also the text copy for the "GO" button and the default text aren't changed?

**Comment by adamespn** [comment]
Sounds like we need a test plan with steps and expected results. I'll make one and you can change the expected results

**Comment by jiakeliu** [comment]
The keyboard still blocks the view when creating a bet, creating a comment, etc. 

Can we make it so when the keyboard pops up on screen, a user can tap ANYWHERE besides the text field to dismiss the keyboard?

**Comment by jiakeliu** [comment]
The comment copy is not changed, it should be "Add a comment..." as the placeholder grey text in the comment field, and the "GO" button should read "ADD". 

Also, I still cannot dismiss the keyboard when tapping anywhere else on the screen. Please reopen this ticket.

**Comment by CodySwannGT** [comment]
@jiakeliu go ahead and open a separate ticket for "The comment copy is not changed, it should be "Add a comment..." as the placeholder grey text in the comment field, and the "GO" button should read "ADD"."

I'll reopen this one

**Comment by jiakeliu** [comment]
Opened #101 for the Comment view visual change. 

This ticket exclusively addresses the keyboard dismissal issue on any screen that activates the on-screen keyboard.

**Comment by husseinm** [comment]
Is this still going on?

**Comment by jiakeliu** [comment]
Yes, this was still an issue in the last release.

**Comment by husseinm** [comment]
All these issues should be resolved in the next release - the text/button should have the correct color + placeholder, the keyboard should also be dismissible by the return button

**Comment by jiakeliu** [comment]
Fixed! Closing.
