### ISSUE TITLE
Bottom Navbar. 

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/thumbwar-ios-client#58]
some screens dont have a bottom bar and I think it may be a mistake.  It feels off when there is no bar.  What do you guys think?

**Comment by smummolo** [comment]
put the bar in on all pages - agree OR have the top / bottom navs appear / disappear (like on pinterest) when you scroll up or down. Either way.

**Comment by adamespn** [comment]
We have modal-type screens that do not have a nav bar because (apparently) you dismiss the screen to return to a screen with a nav bar. We might need some additional design for this. Can you think through some scenarios. For example, how does the bet response screen work? What tab is it in? What happens if I tab away from the "bet response" screen and then tab back? (etc)

**Comment by smummolo** [comment]
im having trouble following this - sorry, can you explain differently?

**Comment by adamespn** [comment]
Should this be closed?

**Comment by jiakeliu** [comment]
Yes
