### ISSUE TITLE
Drop support for attaching images to thumbwars and use default image for backgrounds

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/thumbwar-ios-client#70]

**Comment by jiakeliu** [comment]
As discussed in #36, I think attaching a background image to a post is important. I find myself paying more attention to the posts with an image vs just plain text. Was the decision to drop support for image attachment due to clashing with the white text? The gray overlay should solve this problem right?

**Comment by adamespn** [comment]
Removed this ticket
